### ISSUE TITLE
Error - blank page when add Links in links manager

### ISSUE THREAD

**Issue by alain01** [XoopsModules25x/mymenus#19]
XOOPS 2.5.11 - PHP7.3
Mymenus 1.54 beta 2

- Installation : ok
- Menu manager ok 
- Add menu in menu manager : ok
- Menu Links manager : ok when it's empty
- Add link in links manager : error 
 - Then cant back to the links manager page

Error : 
Erreur: Error: Class 'XoopsModules/Mymenus/Builder' not found dans le fichier /modules/mymenus/class/LinksUtility.php ligne 57

**Comment by zyspec** [comment]
I believe all that needs to be done to "fix" this is to change the name of ./class/builder.php to ./class/Builder.php

**Comment by alain01** [comment]
You mean 
renamed /modules/mymenus/class/builder.php to /modules/mymenus/class/Builder.php

That's all ? 
OMG...
Thank you !

**Comment by mambax7** [comment]
Thanks, Zyspec! I fixed that in my fork, and I've added some new stuff, like a Feedback tab. 
Alain, you can try these changes at: https://github.com/mambax7/mymenus

**Comment by alain01** [comment]
ok, i will test your github repository.
i 'm happy that this module (from Solo71, a belgium man that i met) is updated.
This module was amazing for webmasters who didnt want work with php/html/smarty code.
Very usefull module and very flexible

**Comment by mambax7** [comment]
The module from Solo71 was MultiMenu: https://xoops.org/modules/news/article.php?storyid=3043
MyMenus is a module developed by Ricardo Costa (aka Trabis)

**Comment by alain01** [comment]
ha, ok, anyway, i will try it
