### ISSUE TITLE
Fatal Error on Links Manager

### ISSUE THREAD

**Issue by bleekk** [XoopsModules25x/mymenus#5]
Just installed the RC Version on a fresh Xoops 2.5.7.1
First I created a Menu then tried to go to Links Manager which fails

Fatal error: Can't use method return value in write context in C:\xampp\htdocs\dev_xoops\modules\mymenus\admin\links.php on line 342

**Comment by mambax7** [comment]
Replace the line there 
if (empty($linksObj->getVar('mid'))) { // initial menu value not set

with this:
if (!($linksObj->getVar('mid'))) { // initial menu value not set
